characters = {
    1: {"name": "Hero", "type": "Protagonist"},
    2: {"name": "Villain", "type": "Antagonist"},
    3: {"name": "Sidekick", "type": "Supporting"},
    4: {"name": "Mentor", "type": "Supporting"},
}
emotions = {
    1: "happy",
    2: "sad",
    3: "angry",
    4: "bore",
    5: "content",
    6: "glare",
    7: "sarcasm",
    8: "worried",
    9: "crazy",
    10: "evil_laugh",
    11: "lust",
    12: "shock",
    13: "silly",
    14: "spoked",
}
body_actions = {
    1: "achieve",
    2: "answer",
    3: "explain",
    4: "me",
    5: "not_me",
    6: "question",
    7: "technical",
    8: "why",
    9: "achieve",
    10: "answer",
    11: "chilling",
    12: "come",
    13: "confuse",
    14: "crazy",
    15: "dancing",
    16: "explain",
    17: "feeling_down",
    18: "hi",
    19: "i",
    20: "idea",
    21: "idk",
    22: "joy",
    23: "jumping",
    24: "kung_fu",
    25: "love",
    27: "meditation",
    28: "model",
    30: "paper",
    31: "praying",
    32: "question",
    33: "running",
    34: "search",
    35: "shy",
    36: "singing",
    37: "sneaky",
    38: "standing",
    39: "technical",
    40: "that",
    41: "thinking",
    42: "this",
    43: "what",
    44: "why",
    45: "winner",
    46: "yeah",
    47: "you",
}

screen_mode = {
    1: {
        "name": "office",
        "details": "Use this background when the content is formal, professional, or business-related.",
    },
    2: {
        "name": "explanation",
        "details": "Apply this background when providing detailed explanations, tutorials, or educational content.",
    },
    3: {
        "name": "white",
        "details": "Use this background for a clean, minimalistic look, ideal for content that requires focus without distractions.",
    },
    4: {
        "name": "plain",
        "details": "Apply this background for neutral content that doesn’t need any specific emphasis or theme.",
    },
    5: {
        "name": "green",
        "details": "Use this background when you plan to add a virtual background or need flexibility for future editing.",
    },
}
