characters = {
    1: {"name": "Hero", "type": "Protagonist"},
    # 2: {"name": "Villain", "type": "Antagonist"},
    # 3: {"name": "Sidekick", "type": "Supporting"},
    # 4: {"name": "Mentor", "type": "Supporting"},
}
emotions = {
    1: "happy",
    2: "sad",
    3: "angry",
    4: "bore",
    5: "content",
    6: "glare",
    7: "sarcasm",
    8: "worried",
    9: "crazy",
    10: "evil_laugh",
    11: "lust",
    12: "shock",
    13: "silly",
    14: "spoked",
}
body_actions = {
    1: "achieve",
    2: "answer",
    3: "explain",
    4: "me",
    5: "not_me",
    6: "question",
    7: "technical",
    8: "why",
    9: "achieve",
    10: "answer",
    11: "chilling",
    12: "come",
    13: "confuse",
    14: "crazy",
    15: "dancing",
    16: "explain",
    17: "feeling_down",
    18: "hi",
    19: "i",
    20: "idea",
    21: "idk",
    22: "joy",
    23: "jumping",
    24: "kung_fu",
    25: "love",
    27: "meditation",
    28: "model",
    30: "paper",
    31: "praying",
    32: "question",
    33: "running",
    34: "search",
    35: "shy",
    36: "singing",
    37: "sneaky",
    38: "standing",
    39: "technical",
    40: "that",
    41: "thinking",
    42: "this",
    43: "what",
    44: "why",
    45: "winner",
    46: "yeah",
    47: "you",
}

screen_mode = {
    1: {"name": "office", "details": "For professional and business content."},
    2: {"name": "explanation", "details": "For educational or tutorial content."},
    3: {"name": "white", "details": "For a clean, distraction-free look."},
    4: {"name": "plain", "details": "For neutral content without emphasis."},
    5: {"name": "green", "details": "For virtual backgrounds or editing."},
    6: {"name": "abandant-street", "details": "For deserted or quiet outdoor scenes."},
    7: {"name": "bar", "details": "For casual or social content."},
    8: {"name": "bedroom-1", "details": "For cozy, intimate indoor scenes."},
    9: {"name": "bedroom-2", "details": "For personal, relaxed indoor content."},
    10: {"name": "black", "details": "For dramatic or focused content."},
    11: {"name": "classroom", "details": "For educational or learning environments."},
    12: {"name": "dining-room", "details": "For family or social meal settings."},
    13: {"name": "dream-forest", "details": "For fantasy or surreal content."},
    14: {
        "name": "empty-classroom",
        "details": "For learning-related content in quiet settings.",
    },
    15: {"name": "forest", "details": "For natural, outdoor settings."},
    16: {"name": "garden", "details": "For nature-focused or calm scenes."},
    17: {"name": "green-backyard", "details": "For outdoor, peaceful content."},
    18: {
        "name": "indoor-living-room-and-study-area",
        "details": "For home or personal workspaces.",
    },
    19: {"name": "kitchen", "details": "For cooking or home-based content."},
    20: {"name": "kitchen-and-dining-room", "details": "For social or family meals."},
    21: {"name": "kitchen-dining", "details": "For relaxed meal settings."},
    22: {
        "name": "library-and-book-shop",
        "details": "For reading or knowledge-focused content.",
    },
    23: {"name": "living-room-1", "details": "For casual, home-based scenes."},
    24: {"name": "living-room-2", "details": "For social or relaxed home settings."},
    25: {"name": "outdoor-cafe", "details": "For casual, outdoor social settings."},
    26: {"name": "park", "details": "For outdoor, nature-based scenes."},
    27: {"name": "sitting-area", "details": "For relaxed or social indoor settings."},
    28: {"name": "store", "details": "For shopping or commercial content."},
    29: {"name": "street", "details": "For urban or outdoor public scenes."},
    30: {"name": "train-station", "details": "For travel-related or busy scenes."},
    31: {"name": "yellow", "details": "For bright, happy, or warm content."},
}


# ['abandant-street','bar', 'bedroom-1','bedroom-2','black','classroom','dining-room','dream-forest','empty-classroom','explanation','forest','garden','green','green-backyard','indoor-living-room-and-study-area','kitchen','kitchen-and-dining-room','kitchen-dining','library-and-book-shop','living-room-1','living-room-2','office','outdoor-cafe','park','plain','sitting-area','store','street','train-station','white','yellow']
